apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/leohauschild/local-study-environment.git
      targetRevision: &revision "HEAD"
      path: argocd/applicationsets
      directory:
        recurse: true
    - repoURL: https://github.com/leohauschild/local-study-environment.git
      targetRevision: *revision
      path: argocd/projects