name: 'Terragrunt'
on:
  - pull_request

jobs:
  #https://github.com/dorny/paths-filter?tab=readme-ov-file#examples
  changes:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read
      contents: read

    steps:
      - name: check checkout
        uses: actions/checkout@main

      - name: check changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          list-files: json
          filters: |
            terragrunt:
              - added|modified: '**'
